Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  
  config.vm.provision "shell" do |shell|
    shell.path = "app.sh"
  end
end