#!/usr/bin/env groovy
// The above line is used to trigger correct syntax highlighting.

pipeline {
    // Lets Jenkins use Docker for us later.
    agent any    

    environment {
        registry = "alexandercoolio/devops_app"
        GOCACHE = "/tmp"
    }

    // If anything fails, the whole Pipeline stops.
    stages {
        stage('Build') {   
            // Use golang.
            agent { docker { image 'golang' } }

            steps {                                           
                // Create our project directory.
                sh 'cd ${GOPATH}/src'
                sh 'mkdir -p ${GOPATH}/src/app'

                // Copy all files in our Jenkins workspace to our project directory.                
                sh 'cp -r ${WORKSPACE}/*.go ${GOPATH}/src/app'

                // Build the app.
                sh 'go build'               
            }            
        }

        stage('Test') {
            // Use golang.
            agent { docker { image 'golang' } }

            steps {                 
                // Create our project directory.
                sh 'cd ${GOPATH}/src'
                sh 'mkdir -p ${GOPATH}/src/app'

                // Copy all files in our Jenkins workspace to our project directory.
                sh 'cp -r ${WORKSPACE}/*.go ${GOPATH}/src/app'

                // Remove cached test results.
                sh 'go clean -cache'

                // Run Unit Tests.
                sh 'go test ./... -v -short'            
            }
        }    

        
        stage('Publish Image') {
            environment {
                registryCredential = 'my-docker-credentials-id'
            }
            steps{
                script {

                    def image = docker.build registry + ":v$BUILD_NUMBER"  

                    // Use the Credential ID of the Docker Hub Credentials we added to Jenkins.
                    docker.withRegistry('', registryCredential ) {

                        // Push image and tag it with our build number for versioning purposes.
                        image.push()
                    }
                }
            }
        }

    }

    post {
        always {
            // Clean up our workspace.
            deleteDir()
        }
    }
}   
