---
- name: Deploy the application to server
  hosts: server
  remote_user: vagrant
  become: yes
  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ image }}"
        source: pull

    - name: Running the container
      docker_container:
        image: "{{ image }}"
        state: running
            
    - name: Check if container is running
      shell: docker ps