---
- name: Deploy the application to server
  hosts: server
  remote_user: vagrant
  become: yes
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Stop the old container
        docker_container:
          name: devops_app
          state: stopped

    - name: Prune everything (including non-dangling images)
        docker_prune:
          containers: yes
          images: yes
          images_filters:
            dangling: false
          networks: yes
          volumes: yes
          builder_cache: yes
        
    - name: Pull default Docker image
      docker_image:
        name: "{{ image }}"
        source: pull

    - name: Running the container
      docker_container:
        image: "{{ image }}"
        name: "devops_app"
        state: started
        network_mode: host
        exposed_ports:
          - 5000