---
- name: Deploy the application to server
  hosts: server
  remote_user: vagrant
  become: yes
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
        
    - name: Pull default Docker image
      docker_image:
        name: "{{ image }}"
        source: pull

    - name: Running the container
      docker_container:
        image: "{{ image }}"
        name: "devops_app"
        state: present
        detach: yes
        recreate: yes
        restart: yes
        exposed_ports:
          - 5000
            
    - name: Check if container is running
      shell: docker ps