Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  
  config.vm.provision "shell" do |shell|
    shell.path = "deployment.sh"
  end
end